# Docker Compose File for Application Container
version: "3.8"

services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    command: sleep infinity

    ports:
      - "3000:3000"
      - "5137:5137"
